name: Compile and bench

on:
  push:
    branches:
      - master
      - upstream-pr
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
    inputs: {}

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        opam_file:
          - 'coq-certicoq.opam'
        image:
          - 'mattam82/metacoq:metacoq-1.3.2-coq-8.19'
      fail-fast: false  # don't stop jobs if one fails
    steps:
      - uses: actions/checkout@v3
        with:
           submodules: true
      - uses: coq-community/docker-coq-action@v1
        with:
          custom_image: ${{ matrix.image }}
          opam_file: ${{ matrix.opam_file }}
          before_install: | # comment back in if MetaCoq commit changes
            startGroup "fix permission issues"
              sudo chown -R coq:coq .
            endGroup
            # startGroup "opam pin"
            #   opam pin -n -y submodules/metacoq
            # endGroup
          before_script: |
            startGroup "Install more dependencies"
              sudo apt install --yes wabt curl
              # Node in debian bookworm is too old, install via nodesource
              # TODO once version 22 is in the standard debian repo, use that
              sudo curl -fsSL https://deb.nodesource.com/setup_22.x -o nodesource_setup.sh
              sudo bash nodesource_setup.sh
              sudo apt install -y nodejs
              node --version
            endGroup
            startGroup "fix permission issues"
              sudo chown -R coq:coq .
            endGroup
            startGroup "Copy repo (for later benchmarking)"
              cp -r `pwd` ~/repo
            endGroup
          after_script: |
            startGroup "List installed packages"
              opam list
            endGroup
            startGroup "Run benchmarks"
              make -C ~/repo/benchmarks all
            endGroup
            startGroup "Test bootstrapped plugins"
              cd ~/repo && ./configure.sh global
              make -C ~/repo/bootstrap test
            endGroup
